# Generated by Django 4.0.7 on 2022-09-08 01:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='description',
        ),
        migrations.AddField(
            model_name='artefact',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
