# Generated by Django 4.0.7 on 2022-09-02 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('public_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('manufacture_year', models.CharField(max_length=255)),
                ('markings', models.TextField(blank=True)),
                ('classification', models.CharField(max_length=255)),
                ('provenance', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('length', models.DecimalField(decimal_places=3, max_digits=10)),
                ('height', models.DecimalField(decimal_places=3, max_digits=10)),
                ('width', models.DecimalField(decimal_places=3, max_digits=10)),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
