# Generated by Django 4.0.7 on 2022-09-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_artefact_description_artefact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
