# Generated by Django 4.0.7 on 2022-09-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artefact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='diameter',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='length',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='volume',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
