# Generated by Django 4.0.7 on 2022-09-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_artefact_diameter_alter_artefact_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
