# Generated by Django 4.0.7 on 2022-09-08 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_artefact_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipwreck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('public_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(max_length=255)),
                ('rig_type', models.CharField(max_length=255)),
                ('year_wrecked', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gen_history', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('public_id', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(max_length=255)),
                ('year_wrecked', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('gen_history', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
