# Generated by Django 4.0.7 on 2022-08-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_region_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
