# Generated by Django 4.0.7 on 2022-08-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_is_region_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_region_enabled',
        ),
    ]
