# Generated by Django 4.0.7 on 2022-08-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
