# Generated by Django 4.0.7 on 2022-08-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_user_is_region_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('TAS', 'Tasmania'), ('NSW', 'New South Wales'), ('SA', 'South Australia'), ('VIC', 'Victoria'), ('WA', 'Western Australia'), ('OTHER', 'Other')], default='OTHER', max_length=5),
        ),
    ]
