# Generated by Django 4.0.7 on 2022-08-25 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_record_region_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='records',
        ),
        migrations.AddField(
            model_name='record',
            name='region',
            field=models.ForeignKey(default='OTHER', on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
