# Generated by Django 4.0.7 on 2022-08-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_region_records_record_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(choices=[('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('TAS', 'Tasmania'), ('NSW', 'New South Wales'), ('SA', 'South Australia'), ('VIC', 'Victoria'), ('WA', 'Western Australia'), ('SB', 'Solomon Islands'), ('COMM', 'Commonwealth'), ('OTHER', 'Other'), ('ALL', 'All'), ('NFK', 'Norfolk Island')], default=0, max_length=5),
        ),
    ]
