# Generated by Django 4.0.7 on 2022-08-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_region_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='region',
            field=models.ManyToManyField(to='core.region'),
        ),
    ]
