# Generated by Django 4.0.7 on 2022-08-26 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_record_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='region',
        ),
        migrations.AddField(
            model_name='record',
            name='region',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
