# Generated by Django 4.0.7 on 2022-08-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_record_region_alter_region_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(choices=[('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('TAS', 'Tasmania'), ('NSW', 'New South Wales'), ('SA', 'South Australia'), ('VIC', 'Victoria'), ('WA', 'Western Australia'), ('SB', 'Solomon Islands'), ('COMM', 'Commonwealth'), ('OTHER', 'Other'), ('ALL', 'All'), ('NFK', 'Norfolk Island'), ('DEF', 'Default')], default=1, max_length=5),
        ),
    ]
