# Generated by Django 4.0.7 on 2022-08-26 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_record_region_record_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
