# Generated by Django 4.0.7 on 2022-08-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_region_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='region',
        ),
    ]
