# Generated by Django 4.0.7 on 2022-08-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_record_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='region',
        ),
        migrations.AddField(
            model_name='record',
            name='region',
            field=models.ManyToManyField(to='core.region'),
        ),
    ]
